name: Build Worker
on:
  workflow_dispatch: {}
  push:
    paths:
      - "worker/*"

jobs:
  build:
    env:
      imageName: swdb-worker
      registry: docker.pkg.github.com
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Docker image
        run: |
          docker build api -t ${{ env.registry }}/${{ github.repository }}/${{ env.imageName }}:{{ github.sha }}
          docker push ${{ env.registry }}/${{ github.repository }}/${{ env.imageName }}
